inverntory_management/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"   


urlpatterns = [
    path("signup", views.signup_request, name="signup"),
    path('login', views.login_request, name="login"),
    path('logout',views.logout_request, name='logout')
]

inverntory_management/inverntory_management/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
]

inverntory_management/products/urls.py
from . import views
from django.urls import path

app_name = "products"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:prod_id>/', views.detail, name='detail'),
    path('search/', views.product_search, name="search"),
    path('update/',views.update_product, name='update'),
    path('delete',views.delete_product, name='delete'),
    path('delete',views.delete_product, name='delete'),
    path('add/', views.add_product, name='add')
]

inverntory_management/products/models.py
from accounts.models import my_user
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500, blank=True)
    company_name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
         my_user, related_name='products', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

inverntory_management/products/forms/product_form.py
from products.models import Product
from django import forms

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'company_name', 'description','price']

inverntory_management/products/views.py
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

from products.models import Product
from django.shortcuts import render
from django.http import HttpResponse
from django.template.loader import render_to_string



@login_required(login_url='/accounts/login')
def index(request):
    products = Product.objects.order_by('-created_at')
    context = {"products": products}
    return render(request, 'products/index.html', context)

@login_required(login_url='/accounts/login/')
def detail(request, prod_id):
    try:
        product = Product.objects.get(pk=prod_id)
    except Product.DoesNotExist:
        return render(request, 'products/error.html', {'error': {'error_code': 404, 'error_message': 'Product not found '}})

    return render(request, 'products/details.html', {'prod': product})

@login_required(login_url='/accounts/login')
def product_search(request):
    url_param = request.GET.get('q')
    if url_param:
        products = Product.objects.filter(name__icontains=url_param)
    else:
        products = Product.objects.all()
    
    data = render_to_string(
        template_name = 'products/products_partial.html',
        context = {'products':products}
    )
    data_dict = {'html_from_view': data}
    return JsonResponse(data=data_dict, safe=False)

def detail(request, prod_id):
    try:
        product = Product.objects.get(pk=prod_id)
    except Product.DoesNotExist:
        return render(request, 'products/error.html', {'error': {'error_code':404, 'error_message':'Product not found '}})

    return render(request, 'products/details.html', {'prod': product})

def product_search(request):
    url_param = request.GET.get('q')
    if url_param:
        products = Product.objects.filter(name__icontains=url_param)
    else:
        products = Product.objects.all()
    
    data = render_to_string(
        template_name = 'products/products_partial.html',
        context = {'products':products}
    )
    data_dict = {'html_from_view': data}
    return JsonResponse(data=data_dict, safe=False)

@login_required(login_url='/accounts/login')
def update_product(request):
    # id = request.post.get('id')
    # prod = Product.objects.get(pk=id)
    # prod.name = request.post.get('name')
    # prod.company_name = request.post.get('company_name')
    # prod.price = request.post.get('price')
    # prod.description = request.post.get('description')
    # # save modified product
    # prod.save()

    if request.method == 'POST':
        id = request.GET.get('q')
        model = Product.objects.get(pk=id)
        form = ProductForm(request.POST, instance=model)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            return redirect('/products/')
    else:
        id = request.GET.get('q')
        prod = Product.objects.get(pk=id)
        form = ProductForm(instance=prod)
        return render(request, 'products/edit.html', {'form': form, 'ctx':str(id)})

@login_required(login_url='/accounts/login')
def add_product(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ProductForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            new_product = form.save(commit=False)
            new_product.created_by = request.user
            new_product.save()
            return redirect('/products/')
    else:
        form = ProductForm()
        return render(request, 'products/edit.html', {'form': form})

inverntory_management/products/templates/products/details.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Products</title>
  </head>
  <body>
    <h1>{{ prod.name }}</h1>
    <ul>
      <b>Description:</b> {{prod.description}}
      <br>
      <b>Company Name:</b> {{prod.company_name}}
      <br>
      <b>Price:</b> {{prod.price}}
    </ul>
  </body>
</html>

inverntory_management/products/templates/products/edit.html
{% load crispy_forms_tags %}         
<form action="" method="post">
    {% csrf_token %}
    {{ form |crispy  }}
    <input type="submit" value="Submit">
</form>

inverntory_management/products/templates/products/error.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Products</title>
  </head>
  <body>
   <h1>{{ error.error_code }}</h1>
    <h1>{{ error.error_message }}</h1>
  </body>
</html>

inverntory_management/products/templates/products/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Products</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </meta>
  </head>
<body>

 <nav class="navbar navbar-expand-lg navbar-light bg-light">
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if user.is_authenticated %}
     
      <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Welcome, {{user.username}}</a>
      </li>
    </ul>
    
    <ul class='navbar-nav ml-auto'>
      <li class="nav-item ">
        <a class="nav-link" href="/accounts/logout">Logout</a>
      </li>
     </ul>

           {% endif %}
  </div>
  </nav>
    <div class="container">
      <div class="row">
        <div class="col text-center">
          <a class='btn btn-primary align-center mt-2' href="/products/add" >Add New Product</a>
        </div>
      </div>
   
      <div class="row">
        <div class="col text-center">
          <label for='user-input' class="col-12 mt-2">Search Product</label>
          <input type="text" class="mb-2" id="user-input" name='user-input' />
        </div>
      </div>
      <div id="replaceable-content">
        {% include 'products/products_partial.html' %}
      </div>
    </div>
  </body>
  {% comment %}
  <script
    type="text/javascript"
    src="{{ STATIC_URL }} /static/jquery-3.6.0.min.js"
  ></script>
  {% endcomment %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

  <script>
    const user_input = $("#user-input");
    const products_div = $("#replaceable-content");
    const endpoint = "/products/search";
    const delay_by_in_ms = 700;
    let scheduled_function = false;

    let ajax_call = function (endpoint, request_parameters) {
      $.getJSON(endpoint, request_parameters).done((response) => {
        products_div.html(response["html_from_view"]);
      });
    };

    user_input.on("keyup", function () {
      const request_parameters = {
        q: $(this).val(),
      };

      // if scheduled_function is NOT false, cancel the execution of the function
      if (scheduled_function) {
        clearTimeout(scheduled_function);
      }
      scheduled_function = setTimeout(
        ajax_call,
        delay_by_in_ms,
        endpoint,
        request_parameters
      );
    });


    function del(id) {
      var result = confirm("Are you sure...? You want to delete this Product?");
      if (result) {
        $.getJSON("/products/delete", { q: id }).done((response) => {
          products_div.html(response["html_from_view"]);
        });
      }
    }
  </script>
</html>

inverntory_management/products/templates/products/products_partial.html
{% if products %}
<table class='table table-dark'>
<tr>
    <th>Product Name</th>
    <th>Edit</th> 
    <th>Delete</th>
  </tr>
  {% for prod in products %}
  <tr >
    <td class="text-center"><a href="{% url 'products:detail' prod.id %}">{{ prod.name }}</a></td>
    <td class="text-center"><a class='btn btn-warning' href="update/?q={{prod.id}}">Edit</a></td> 
    <td class="text-center"><button class='btn btn-danger' onclick="del({{prod.id}})">Delete</button></td>
  </tr>
    {% endfor %}
</table>

{% else %}
<p>No products are available.</p>
{% endif %}